#  Copyright 2023-2024 Dataport AöR
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

logging:
  level:
    org.springframework.security: DEBUG

spring:
  h2:
    console.enabled: true
  profiles:
    active: default
  datasource:
    url: jdbc:h2:file:./database.db
    username: sa
    password:
    driverClassName: org.h2.Driver
    initialization-mode: always
  jackson:
    mapper:
      DEFAULT_VIEW_INCLUSION: true
  jpa:
    generate-ddl: true
    ddl:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: false
        use_sql_comments: true
        format_sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
  cloud:
    bus:
      enabled: true
      refresh:
        enabled: true

server:
  port: 443
  error:
    include-stacktrace: "never"
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: "example"
    key-store-type: PKCS12
    key-alias: tomcat
    enabled: true
  http:
    port: 8088

management:
  endpoints:
    enabled-by-default: false
    web:
      base-path: "/"
  endpoint:
    health:
      enabled: true

did-domain: "localhost"

cors:
  global:
    origins:
    patterns: >
      http://localhost:[*]

certificate-issuer: "MERLOT Federation"

merlot-cert-path: ""
merlot-verification-method-enabled: true